# Generated by Django 3.0.4 on 2020-04-01 06:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20200331_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='time'),
        ),
    ]
